import { ReactNode } from 'react'
import { Metadata } from 'next'

import StylesProvider from '~/styles/styles-provider'
import BottomNavigation from '~/components/bottom-navigation'
import TrpcProvider from '~/helpers/trpc/trpc-provider'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  manifest: '/manifest.json',
}

function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <StylesProvider>
          <TrpcProvider>
            {children}
            <BottomNavigation />
          </TrpcProvider>
        </StylesProvider>
      </body>
    </html>
  )
}

export default RootLayout
