export const SPORTS = [
  { value: 'soccer', label: 'soccer' },
  { value: 'basketball', label: 'basketball' },
  { value: 'tennis', label: 'tennis' },
  { value: 'volleyball', label: 'volleyball' },
  { value: 'baseball', label: 'baseball' },
  { value: 'golf', label: 'golf' },
  { value: 'hockey', label: 'hockey' },
  { value: 'skate', label: 'skate' },
  { value: 'skateboard', label: 'skateboard' },
  { value: 'bmx', label: 'bmx' },
  { value: 'football', label: 'football' },
  { value: 'rugby', label: 'rugby' },
  { value: 'cricket', label: 'cricket' },
  { value: 'badminton', label: 'badminton' },
  { value: 'table tennis', label: 'table tennis' },
  { value: 'handball', label: 'handball' },
  { value: 'bowling', label: 'bowling' },
  { value: 'billiards', label: 'billiards' },
  { value: 'pool', label: 'pool' },
  { value: 'darts', label: 'darts' },
  { value: 'gym', label: 'gym' },
  { value: 'yoga', label: 'yoga' },
  { value: 'fitness', label: 'fitness' },
  { value: 'crossfit', label: 'crossfit' },
  { value: 'climbing', label: 'climbing' },
  { value: 'swimming', label: 'swimming' },
  { value: 'surfing', label: 'surfing' },
  { value: 'kitesurfing', label: 'kitesurfing' },
  { value: 'windsurfing', label: 'windsurfing' },
  { value: 'diving', label: 'diving' },
  { value: 'snorkeling', label: 'snorkeling' },
  { value: 'fishing', label: 'fishing' },
  { value: 'hiking', label: 'hiking' },
  { value: 'running', label: 'running' },
  { value: 'cycling', label: 'cycling' },
  { value: 'skating', label: 'skating' },
  { value: 'skiing', label: 'skiing' },
  { value: 'snowboarding', label: 'snowboarding' },
  { value: 'chess', label: 'chess' },
  { value: 'poker', label: 'poker' },
  { value: 'board games', label: 'board games' },
  { value: 'video games', label: 'video games' },
  { value: 'paintball', label: 'paintball' },
  { value: 'airsoft', label: 'airsoft' },
]
